package:
  name: arro3-core
  version: 0.2.1
  top-level:
    - "arro3.core"
source:
  url: https://github.com/kylebarron/arro3/releases/download/py-v0.2.1/arro3_core-0.2.1-cp38-abi3-emscripten_3_1_58_wasm32.whl
  sha256: 91be0594e224332813316d6d659618d5d1187faf2232b148ab32c8fe747ee32e
requirements:
extra:
  recipe-maintainers:
    - kylebarron
