package:
  name: arro3-compute
  version: 0.2.1
  top-level:
    - "arro3.compute"
source:
  url: https://github.com/kylebarron/arro3/releases/download/py-v0.2.1/arro3_compute-0.2.1-cp38-abi3-emscripten_3_1_58_wasm32.whl
  sha256: ba412caa87fd00b9f305cc213f4d0555db5b1efb675979d01c517ecb6050698f
requirements:
  run:
    - arro3-core
extra:
  recipe-maintainers:
    - kylebarron
